TripsLogApp/Models/TripDetail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace TripsLogApp.Models
{
    public class TripDetail
    {
        // EF will instruct the database to automatically generate this value
        public int TripDetailID { get; set; }
        
        [Required(ErrorMessage = "Please Enter a Destination")]    
        public string Destination { get; set; }
       
        public string Accomodations { get; set; }

        [Required(ErrorMessage = "Please Enter a start date")]
        [DataType(DataType.Date, ErrorMessage = "Please Enter a valid date")]
        public DateTime StartDate { get; set; }

        [DataType(DataType.Date, ErrorMessage = "Please Enter a valid date")]
        [Required(ErrorMessage = "Please Enter an end start date")]
        public DateTime EndDate { get; set; }

       
        [DataType(DataType.PhoneNumber, ErrorMessage = "Phone number must be valid.")]
        public string PhoneNumber { get; set; }
        
        [DataType(DataType.EmailAddress, ErrorMessage = "Email must be valid.")]
        public string Email { get; set; }       
        public string FirstThingToDo { get; set; }        
        public string SecondThingToDo { get; set; }        
        public string ThirdThingToDo { get; set; }

        public string Slug =>
            Destination?.Replace(' ', '-').ToLower() + '-' + Accomodations?.Replace(' ', '-').ToLower();
    }
}

TripsLogApp/Models/TripDetailContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace TripsLogApp.Models
{
    public class TripDetailContext : DbContext
    {
        public TripDetailContext(DbContextOptions<TripDetailContext> options)
            : base(options)
        { }

        public DbSet<TripDetail> TripDetails { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TripDetail>().HasData(
                new TripDetail
                {
                    TripDetailID = 1,
                    Destination = "Louisville",
                    Accomodations = "the Galt House",
                    StartDate = new DateTime(2008, 3, 1),
                    EndDate = new DateTime(2009, 3, 1),
                    PhoneNumber = "502-555-9999",
                    Email = "Trip1@gmail.com",
                    FirstThingToDo = "Go to the Derby",
                    SecondThingToDo = "Go drink bourbon",
                    ThirdThingToDo = "Go eat Pizza"


                },
                new TripDetail
                {
                    TripDetailID = 2,
                    Destination = "Gatlinburg",
                    Accomodations = "An AirBnB",
                    StartDate = new DateTime(2022, 3, 1),
                    EndDate = new DateTime(2022, 3, 2),
                    PhoneNumber = "502-555-9999",
                    Email = "Trip2@gmail.com",
                    FirstThingToDo = "Go to Cade's Cove",
                    SecondThingToDo = "Go drink moonshine",
                    ThirdThingToDo = "Go eat pancakes"
                });
        }
    }
}

TripsLogApp/Models/TripViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace TripsLogApp.Models
{
    public class TripViewModel
    {
        public TripDetail TripDetail { get; set; }

        public int PageNumber { get; set; }
    }
        
}

TripsLogApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TripsLogApp.Models;
using Microsoft.EntityFrameworkCore;

namespace TripsLogApp.Controllers
{
    public class HomeController : Controller
    {
        private TripDetailContext context { get; set; }

        public HomeController(TripDetailContext ctx)
        {
            context = ctx;
        }

        public IActionResult Index()
        {
            TempData.Clear();

            var trip = context.TripDetails
                .OrderBy(s => s.StartDate)
                .ToList();
            return View(trip);
        }
    }
}

TripsLogApp/Controllers/TripController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TripsLogApp.Models;
using Microsoft.EntityFrameworkCore;

namespace TripsLogApp.Controllers
{
    public class TripController : Controller
    {
        private TripDetailContext context { get; set; }

        public TripController(TripDetailContext ctx)
        {
            context = ctx;
        }

        [HttpGet]
        public ViewResult Add(string id = "")
        {
            var viewModel = new TripViewModel();

            if (id.ToLower() == "trippage2")
            {
                var accomodations = TempData[nameof(TripDetail.Accomodations)]?.ToString();

                if (string.IsNullOrEmpty(accomodations))
                {
                    viewModel.PageNumber = 3;
                    var tripDestination = TempData.Peek(nameof(TripDetail.Destination)).ToString();
                    viewModel.TripDetail = new TripDetail { Destination = tripDestination };
                    return View("TripPage3", viewModel);
                }
                else
                {
                    viewModel.PageNumber = 2;
                    viewModel.TripDetail = new TripDetail { Accomodations = accomodations };
                    TempData.Keep(nameof(TripDetail.Accomodations));
                    return View("TripPage2", viewModel);
                }
            }
            else if (id.ToLower() == "trippage3")
            {
                viewModel.PageNumber = 3;
                viewModel.TripDetail = new TripDetail { Destination = TempData.Peek(nameof(TripDetail.Destination)).ToString() };
                return View("TripPage3", viewModel);
            }
            else
            {
                viewModel.PageNumber = 1;
                return View("TripPage1", viewModel);
            }
        }

        [HttpPost]
        public IActionResult Add(TripViewModel viewModel)
        {
            if(viewModel.PageNumber == 1)
            {
                if (ModelState.IsValid)
                {
                    TempData[nameof(TripDetail.Destination)] = viewModel.TripDetail.Destination;
                    TempData[nameof(TripDetail.Accomodations)] = viewModel.TripDetail.Accomodations;
                    TempData[nameof(TripDetail.StartDate)] = viewModel.TripDetail.StartDate;
                    TempData[nameof(TripDetail.EndDate)] = viewModel.TripDetail.EndDate;
                    return RedirectToAction("Add", new { id = "TripPage2" });
                }
                else
                {
                    return View("TripPage1", viewModel);
                }
            }
            else if (viewModel.PageNumber == 2)
            {
                TempData[nameof(TripDetail.PhoneNumber)] = viewModel.TripDetail.PhoneNumber;
                TempData[nameof(TripDetail.Email)] = viewModel.TripDetail.Email;
                return RedirectToAction("Add", new { id = "tripPage3" });
            }
            else if (viewModel.PageNumber == 3)
            {
                viewModel.TripDetail.Destination = TempData[nameof(TripDetail.Destination)].ToString();
                viewModel.TripDetail.Accomodations = TempData[nameof(TripDetail.Accomodations)]?.ToString();
                viewModel.TripDetail.StartDate = (DateTime)TempData[nameof(TripDetail.StartDate)];
                viewModel.TripDetail.EndDate = (DateTime)TempData[nameof(TripDetail.EndDate)];
                viewModel.TripDetail.PhoneNumber = TempData[nameof(TripDetail.PhoneNumber)]?.ToString();
                viewModel.TripDetail.Email = TempData[nameof(TripDetail.Email)]?.ToString();

                context.TripDetails.Add(viewModel.TripDetail);
                context.SaveChanges();
                TempData["message"] = $"Trip to {viewModel.TripDetail.Destination} added.";
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }        
    }
}

TripsLogApp/Views/Home/Index.cshtml
@model List<TripDetail>

<a asp-controller="Trip" asp-action="Add">Add Trip</a>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Destination</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Accomodations</th>
            <th>Things To Do:</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var trip in Model)
        {
            <tr>
                <td>@trip.Destination</td>
                <td>@trip.StartDate.ToShortDateString()</td>
                <td>@trip.EndDate.ToShortDateString()</td>
                <td>@trip.Accomodations</td>
                <td>@trip.FirstThingToDo <br />@trip.SecondThingToDo <br />@trip.ThirdThingToDo</td>
            </tr>
        }
    </tbody>
</table>

TripsLogApp/Views/Shared/_Layout.cshtml
@{
    string message = TempData["message"]?.ToString();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>TripsLogApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container">
        <header class="jumbotron jumbotron-fluid">
            <h1 class="mt-3 d-flex justify-content-center">My Trip Log</h1>
            <h3 class="d-flex justify-content-center">Oh The Memories</h3>
        </header>
    </div>
    <div class="container">
        <main role="main">
            @if (!string.IsNullOrEmpty(message))
            {
                <h3>class="bg-light text-center p-2 mb-1"@message</h3>
            }
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container text-center">
            <h5>The Trips Logs App. Let's See How Challenging Building This Will Be!!!'</h5>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

TripsLogApp/Views/Trip/TripPage1.cshtml
@model TripViewModel

@{
    ViewBag.Title = "Add Trip Destination and Dates";
}

<h1>@ViewBag.Title</h1>

<form asp-action="Add">
    <input type="hidden" asp-for="PageNumber" />
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="TripDetail.Destination">Destination:</label>
        <input asp-for="TripDetail.Destination" class="form-control">

    </div>

    <div class="form-group">
        <label asp-for="TripDetail.Accomodations">Accomodations:</label>
        <input asp-for="TripDetail.Accomodations" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="TripDetail.StartDate">Start Date:</label>
        <input asp-for="TripDetail.StartDate" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="TripDetail.EndDate">End Date:</label>
        <input asp-for="TripDetail.EndDate" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Next</button>
    <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Cancel</a>
</form>

TripsLogApp/Views/Trip/TripPage2.cshtml
@model TripViewModel

<h1>Add info for the @Model.TripDetail.Accomodations</h1>
<form asp-action="Add">
    <input type="hidden" asp-for="PageNumber" />
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="TripDetail.PhoneNumber">Phone Number:</label>
        <input asp-for="TripDetail.PhoneNumber" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="TripDetail.Email">Email:</label>
        <input asp-for="TripDetail.Email" class="form-control">
    </div>

    <button type="submit" class="btn btn-primary">Next</button>
    <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Cancel</a>
</form>

TripsLogApp/Views/Trip/TripPage3.cshtml
@model TripViewModel
@{
    ViewBag.Title = $"Add things to do in {Model.TripDetail.Destination}";
}
@section scripts {
    <script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/
                       jquery.validate.unobtrusive.min.js"></script>
}

<h1>@ViewBag.Title</h1>

<form asp-action="Add">
    <input type="hidden" asp-for="PageNumber" />
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <input asp-for="TripDetail.FirstThingToDo" class="form-control">
    </div>

    <div class="form-group">
        <input asp-for="TripDetail.SecondThingToDo" class="form-control">
    </div>

    <div class="form-group">
        <input asp-for="TripDetail.ThirdThingToDo" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
    <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Cancel</a>
</form>